//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalManagementEntity : DbContext
    {
        public HospitalManagementEntity()
            : base("name=HospitalManagementEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Medicine_details> Medicine_details { get; set; }
        public virtual DbSet<Patient_Appoinment> Patient_Appoinment { get; set; }
        public virtual DbSet<Patient_record> Patient_record { get; set; }
    }
}
